import type { SimGraph, SimNode, SimEdge, NodeType } from "./types";

export interface GeneratedScript {
  python: string;
}

export function generateSimPyScript(
  graph: SimGraph,
  durationSeconds: number,
  tickIntervalSeconds: number
): GeneratedScript {
  const nodeConfig: Record<string, any> = {};
  for (const node of graph.nodes) {
    nodeConfig[node.id] = {
      nodeType: node.nodeType,
      label: node.label,
      params: node.params,
    };
  }

  const edges = graph.edges.map((e) => ({
    id: e.id,
    source: e.source,
    target: e.target,
  }));

  const python = PYTHON_TEMPLATE
    .replace("{DURATION}", String(durationSeconds))
    .replace("{TICK_INTERVAL}", String(tickIntervalSeconds))
    .replace("{NODE_CONFIG_JSON}", JSON.stringify(nodeConfig))
    .replace("{EDGES_JSON}", JSON.stringify(edges));

  return { python };
}

const PYTHON_TEMPLATE = `
# AUTO-GENERATED by JustCmul8 codeGenerator.ts
import simpy
import random
import math
import json
import logging

# ── Configuration ──────────────────────────────────────────────────────────────
DURATION = {DURATION}
TICK_INTERVAL = {TICK_INTERVAL}
NODE_CONFIG = json.loads(r"""{NODE_CONFIG_JSON}""")
EDGES = json.loads(r"""{EDGES_JSON}""")

# ── Log Buffer ─────────────────────────────────────────────────────────────────
log_buffer = []
entity_counter = [0]
stats = {}
active_processes_by_node = {}
global_events = {}

def next_entity_id():
    entity_counter[0] += 1
    return entity_counter[0]

def log_event(sim_time, entity_id, node_id, node_label, event):
    log_buffer.append({
        "simTime": sim_time,
        "entityId": entity_id,
        "nodeId": node_id,
        "nodeLabel": node_label,
        "event": event
    })

# ── Distributions ──────────────────────────────────────────────────────────────
def sample(dist_type, mean, std=None):
    if dist_type == "exponential":
        return random.expovariate(1.0 / mean) if mean > 0 else 0
    elif dist_type == "uniform":
        return random.uniform(mean * 0.5, mean * 1.5)
    elif dist_type == "normal":
        s = std if std is not None else mean * 0.3
        return max(0, random.gauss(mean, s))
    elif dist_type == "deterministic":
        return max(0, mean)
    elif dist_type == "poisson":
        return random.expovariate(1.0 / mean) if mean > 0 else 0
    else:
        return random.expovariate(1.0 / mean) if mean > 0 else 0

# ── Build adjacency ────────────────────────────────────────────────────────────
out_edges = {}
for edge in EDGES:
    src = edge["source"]
    if src not in out_edges:
        out_edges[src] = []
    out_edges[src].append(edge["target"])

rr_counters = {}
def get_next_targets(node_id, routing_mode="round_robin"):
    """Returns a list of target node IDs based on the routing mode."""
    targets = out_edges.get(node_id, [])
    if not targets:
        return []
    if routing_mode == "broadcast":
        return targets  # send to ALL
    if len(targets) == 1:
        return [targets[0]]
    # Round-robin (default, also used for "priority" as a fallback)
    if node_id not in rr_counters:
        rr_counters[node_id] = 0
    idx = rr_counters[node_id] % len(targets)
    rr_counters[node_id] += 1
    return [targets[idx]]

def get_next_target(node_id):
    """Legacy single-target helper — returns first round-robin target."""
    targets = get_next_targets(node_id, "round_robin")
    return targets[0] if targets else None

def get_target_for_decision(node_id):
    cfg = NODE_CONFIG[node_id]
    routes = cfg["params"].get("routes", [])
    r = random.random()
    cum = 0.0
    for route in routes:
        cum += route["probability"]
        if r <= cum:
            return route["targetId"]
    return routes[0]["targetId"] if routes else None

# ── Stats helpers ──────────────────────────────────────────────────────────────
def init_stats():
    for nid, cfg in NODE_CONFIG.items():
        stats[nid] = {
            "nodeId": nid,
            "nodeType": cfg["nodeType"],
            "label": cfg["label"],
            "entitiesIn": 0,
            "entitiesOut": 0,
            "currentDepth": 0,
            "busyCount": 0,
            "capacity": cfg["params"].get("capacity", 1),
            "waits": [],
            "services": [],
            "utilization": 0.0,
            "avgWaitTime": 0.0,
            "avgServiceTime": 0.0,
            "renegeCount": 0,
        }

def snapshot_stats(env):
    snap = {}
    for nid, s in stats.items():
        util = s["busyCount"] / max(1, s["capacity"]) if s["capacity"] > 0 else 0
        snap[nid] = {
            "nodeId": nid,
            "nodeType": s["nodeType"],
            "label": s["label"],
            "entitiesIn": s["entitiesIn"],
            "entitiesOut": s["entitiesOut"],
            "currentDepth": s["currentDepth"],
            "utilization": min(1.0, util),
            "avgWaitTime": sum(s["waits"]) / len(s["waits"]) if s["waits"] else 0,
            "avgServiceTime": sum(s["services"]) / len(s["services"]) if s["services"] else 0,
            "renegeCount": s.get("renegeCount", 0),
        }
    return snap

# ── Helpers ────────────────────────────────────────────────────────────────────
def handle_resource_lifecycle(env, eid, node_id, cfg, s, resources, queued_at, entity_attrs, req_pri=None, initial_req=None):
    res = resources[node_id]
    params = cfg["params"]
    label = cfg["label"]
    
    if req_pri is None:
        req_pri = entity_attrs.get("priority", 3) + (env.now / 1000000.0)
        
    original_svc_time = sample(
        params.get("serviceDistribution", "exponential"),
        params.get("serviceTimeMean", 1)
    )
    svc_time = original_svc_time
    
    started_service = False
    req = initial_req
    
    while svc_time > 0:
        if req is None:
            req = res.request(priority=req_pri)
            yield req
            
        if not started_service:
            wait_time = env.now - queued_at
            s["waits"].append(wait_time)
            log_event(env.now, eid, node_id, label, "service_start")
            started_service = True
            
        s["busyCount"] += 1
        start = env.now
        
        try:
            yield env.timeout(svc_time)
            svc_time = 0  # Finished!
        except simpy.Interrupt:
            log_event(env.now, eid, node_id, label, "preempted")
            svc_time -= (env.now - start)
        finally:
            s["busyCount"] -= 1
            if req is not None:
                # SimPy PreemptiveResource handles released properly, but we must release the request explicitly 
                # if we were the ones holding it when finished or preempted.
                res.release(req)
                req = None

    s["services"].append(original_svc_time)
    log_event(env.now, eid, node_id, label, "service_end")
    s["currentDepth"] -= 1
    s["entitiesOut"] += 1
    next_id = get_next_target(node_id)
    if next_id:
        yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

# ── SimPy Processes ────────────────────────────────────────────────────────────
def entity_process(env, eid, node_id, resources, entity_attrs=None):
    if entity_attrs is None:
        entity_attrs = {"id": eid, "priority": 3, "entityClass": "standard", "arrivalTime": env.now}
    cfg = NODE_CONFIG.get(node_id)
    if cfg is None:
        return

    node_type = cfg["nodeType"]
    label = cfg["label"]
    s = stats[node_id]
    s["entitiesIn"] += 1
    s["currentDepth"] += 1

    if node_type == "source":
        log_event(env.now, eid, node_id, label, "arrived")
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type == "queue":
        params = cfg.get("params", {})
        
        # ── 1. Capacity Check ──
        capacity = params.get("capacity", -1)
        if capacity != -1 and s["currentDepth"] > capacity:
            log_event(env.now, eid, node_id, label, "rejected")
            s["currentDepth"] -= 1
            return

        log_event(env.now, eid, node_id, label, "queued")
        next_id = get_next_target(node_id)
        
        # If queue is connected to a resource, apply patience timeout and discipline here
        if next_id and NODE_CONFIG.get(next_id, {}).get("nodeType") in ("resource", "priority_resource"):
            dist = params.get("patienceDistribution", "none")
            discipline = params.get("discipline", "FIFO")
            sold_out_threshold = params.get("soldOutThreshold", None)
            broadcast_renege = params.get("broadcastRenege", False)
            
            res_node_id = next_id
            res_cfg = NODE_CONFIG[res_node_id]
            res_s = stats[res_node_id]
            res = resources[res_node_id]
            
            queued_at = env.now
            res_s["entitiesIn"] += 1
            res_s["currentDepth"] += 1
            
            # Determine Request Priority based on Discipline
            if discipline == "FIFO":
                req_pri = env.now
            elif discipline == "LIFO":
                req_pri = -env.now
            elif discipline == "PRIORITY":
                req_pri = entity_attrs.get("priority", 3) + (env.now / 1000000.0)
            else:
                req_pri = env.now
                
            req = res.request(priority=req_pri)
            wait_events = [req]
            
            # Patience setup
            if dist != "none":
                if dist == "uniform":
                    patience = random.uniform(params.get("patienceMin", 1), params.get("patienceMax", 3))
                elif dist == "exponential":
                    mean = params.get("patienceTimeout", 5)
                    patience = random.expovariate(1.0 / mean) if mean > 0 else 0
                elif dist == "deterministic":
                    patience = params.get("patienceTimeout", 5)
                else:
                    patience = float('inf')
                wait_events.append(env.timeout(patience))
                
            # Sold-Out Event
            if sold_out_threshold is not None and broadcast_renege:
                if node_id not in global_events:
                    global_events[node_id] = env.event()
                wait_events.append(global_events[node_id])
                
            results = yield env.any_of(wait_events)
            
            if req in results:
                # Acquired resource!
                s["currentDepth"] -= 1
                s["entitiesOut"] += 1
                
                # Check sold-out condition
                if sold_out_threshold is not None:
                    remaining = res.capacity - res.count
                    if remaining <= sold_out_threshold:
                        if broadcast_renege and node_id in global_events:
                            log_event(env.now, eid, node_id, label, "sold_out")
                            global_events[node_id].succeed()
                            global_events[node_id] = env.event() # Reset for next time
                            
                yield env.process(handle_resource_lifecycle(
                    env, eid, res_node_id, res_cfg, res_s, resources, queued_at, entity_attrs, req_pri, initial_req=req
                ))
            else:
                # Reneged due to timeout or sold_out
                req.cancel()
                log_event(env.now, eid, node_id, label, "reneged")
                s["currentDepth"] -= 1
                s["renegeCount"] = s.get("renegeCount", 0) + 1
                res_s["currentDepth"] -= 1
                return
        else:
            s["currentDepth"] -= 1
            s["entitiesOut"] += 1
            if next_id:
                yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type in ("resource", "priority_resource"):
        res = resources[node_id]
        queued_at = env.now
        log_event(env.now, eid, node_id, label, "queued")
        
        req_pri = entity_attrs.get("priority", 3) + (env.now / 1000000.0)
        yield env.process(handle_resource_lifecycle(
            env, eid, node_id, cfg, s, resources, queued_at, entity_attrs, req_pri=req_pri
        ))

    elif node_type == "service":
        params = cfg["params"]
        svc_time = sample(
            params.get("distribution", "exponential"),
            params.get("durationMean", 1)
        )
        
        def interruptible_delay(env, delay):
            try:
                log_event(env.now, eid, node_id, label, "service_start")
                yield env.timeout(delay)
                log_event(env.now, eid, node_id, label, "service_end")
            except simpy.Interrupt as i:
                log_event(env.now, eid, node_id, label, "interrupted")
                
        p = env.process(interruptible_delay(env, svc_time))
        if node_id not in active_processes_by_node: active_processes_by_node[node_id] = {}
        active_processes_by_node[node_id][eid] = p
        yield p
        if eid in active_processes_by_node[node_id]: del active_processes_by_node[node_id][eid]
        
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type == "decision":
        log_event(env.now, eid, node_id, label, "routed")
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        target_id = get_target_for_decision(node_id)
        if target_id:
            yield env.process(entity_process(env, eid, target_id, resources, entity_attrs))

    elif node_type == "sink":
        log_event(env.now, eid, node_id, label, "completed")
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1

    elif node_type == "store":
        store = resources.get(node_id)
        params = cfg["params"]
        if isinstance(store, simpy.PriorityStore):
            item = simpy.PriorityItem(entity_attrs.get("priority", 3), entity_attrs)
        else:
            item = entity_attrs

        yield store.put(item)
        s["currentDepth"] = len(store.items)
        
        if isinstance(store, simpy.FilterStore):
            prop = params.get("filterProperty", "entityClass")
            op = params.get("filterOperator", "==")
            val = params.get("filterValue", "")
            def filter_func(x):
                actual = x.get(prop, "") if isinstance(x, dict) else ""
                if op == "==": return str(actual) == str(val)
                if op == "!=": return str(actual) != str(val)
                return True
            got = yield store.get(filter_func)
        else:
            got = yield store.get()

        s["currentDepth"] = len(store.items)
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type == "event_trigger":
        evt = global_events.get(node_id)
        if evt and not evt.triggered:
            evt.succeed()
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type in ("any_of", "all_of"):
        sources = [e["source"] for e in EDGES if e["target"] == node_id]
        evts = [global_events[src] for src in sources if src in global_events]
        if evts:
            if node_type == "any_of":
                yield env.any_of(evts)
            else:
                yield env.all_of(evts)
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = cfg["params"].get("targetId") or get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type == "interrupter":
        target = cfg["params"].get("targetNodeId")
        cause = cfg["params"].get("cause", "Interrupted")
        if target and target in active_processes_by_node:
            for p_eid, p in list(active_processes_by_node[target].items()):
                if p.is_alive:
                    p.interrupt(cause)
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    else:
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))


# ── NHPP helpers ──────────────────────────────────────────────────────────────
def _nhpp_rate_at(t, nhpp_rates):
    """Return λ(t) for piecewise-constant rate table (sorted by simTime)."""
    rate = nhpp_rates[0]["rate"] if nhpp_rates else 0.0
    for entry in nhpp_rates:
        if t >= entry["simTime"]:
            rate = entry["rate"]
        else:
            break
    return rate

def _nhpp_thinning(env, nhpp_rates, majorizing_rate):
    """
    Lewis-Shedler Thinning (Acceptance/Rejection) NHPP algorithm.
    Yields inter-arrival times according to λ(t).
    """
    while True:
        inter = random.expovariate(majorizing_rate) if majorizing_rate > 0 else float('inf')
        yield env.timeout(inter)
        current_rate = _nhpp_rate_at(env.now, nhpp_rates)
        if random.random() < current_rate / majorizing_rate:
            return  # accepted — caller resumes

def _nhpp_time_transform(env, nhpp_rates, duration):
    """
    Non-linear Time Transformation NHPP algorithm.
    Generates cumulative hazard inversion via the integrated rate Λ(t).
    Yields a wait until the next transformed arrival time.
    """
    # Build a sorted copy
    rates = sorted(nhpp_rates, key=lambda r: r["simTime"])
    # Accumulate Λ(t) at each breakpoint
    def integrated_rate(t):
        total = 0.0
        prev_time = 0.0
        prev_rate = 0.0
        for entry in rates:
            seg_end = min(entry["simTime"], t)
            if seg_end <= prev_time:
                prev_rate = entry["rate"]
                continue
            total += prev_rate * (seg_end - prev_time)
            if seg_end >= t:
                break
            prev_time = entry["simTime"]
            prev_rate = entry["rate"]
        else:
            # Extrapolate with last known rate
            if t > prev_time:
                total += prev_rate * (t - prev_time)
        return total

    def invert_lambda(target):
        """Find t such that Λ(t) = target (bisection)."""
        lo, hi = env.now, duration
        for _ in range(64):
            mid = (lo + hi) / 2.0
            if integrated_rate(mid) < target:
                lo = mid
            else:
                hi = mid
        return (lo + hi) / 2.0

    lambda_now = integrated_rate(env.now)
    U = random.random()
    next_lambda = lambda_now - math.log(U)
    next_t = invert_lambda(next_lambda)
    wait = max(0.0, next_t - env.now)
    yield env.timeout(wait)

def source_process(env, node_id, resources, total_arrived):
    cfg = NODE_CONFIG[node_id]
    params = cfg["params"]
    label = cfg["label"]

    # ── Core arrival params ────────────────────────────────────────────────────
    arrival_rate      = params.get("arrivalRate", 1)
    distribution      = params.get("distribution", "exponential")
    max_entities      = params.get("maxEntities", None)
    duration_limit    = params.get("durationLimit", None)  # per-source sim-time cap
    routing_mode      = params.get("routingMode", "round_robin")
    schedule          = params.get("schedule", [])
    schedule_recurring= params.get("scheduleRecurring", False)

    # ── NHPP ──────────────────────────────────────────────────────────────────
    nhpp_rates        = params.get("nhppRates", [])
    majorizing_rate   = params.get("nhppMajorizingRate", None)
    if majorizing_rate is None and nhpp_rates:
        majorizing_rate = max(r["rate"] for r in nhpp_rates)

    # ── Batch / entities per arrival ──────────────────────────────────────────
    entities_per_arrival = params.get("entitiesPerArrival", 1)
    batch_dist           = params.get("batchDistribution", "deterministic")

    # ── Entity attributes ─────────────────────────────────────────────────────
    priority_level  = params.get("priorityLevel", "standard")
    entity_class    = params.get("entityClass", "customer")
    entity_labels   = params.get("entityLabels", [])  # [{key, value}, ...]
    priority_map    = {"standard": 3, "priority": 2, "urgent": 1}
    priority_num    = priority_map.get(priority_level, 3)

    # ── Probabilistic part mix ────────────────────────────────────────────────
    part_mix = params.get("partMix", [])  # [{entityClass, weight}, ...]
    if part_mix:
        total_weight = sum(e["weight"] for e in part_mix) or 1.0
        _mix_probs = [(e["entityClass"], e["weight"] / total_weight) for e in part_mix]
    else:
        _mix_probs = []

    def _sample_entity_class():
        if not _mix_probs:
            return entity_class
        r = random.random()
        cumulative = 0.0
        for ec, prob in _mix_probs:
            cumulative += prob
            if r <= cumulative:
                return ec
        return _mix_probs[-1][0]

    # ── Lifecycle hook snippets ────────────────────────────────────────────────
    hook_before_arrival = params.get("onBeforeArrival", "").strip()
    hook_at_exit        = params.get("onAtExit", "").strip()
    hook_on_discard     = params.get("onDiscard", "").strip()

    # ── KPI ───────────────────────────────────────────────────────────────────
    time_measure_start  = params.get("timeMeasureStart", False)

    # ── Shift windows ─────────────────────────────────────────────────────────
    shift_windows = params.get("shiftWindows", [])  # [{startTime, endTime}, ...]

    def _in_shift(t):
        """Return True if sim-time t falls inside any configured shift window."""
        if not shift_windows:
            return True
        for w in shift_windows:
            if w["startTime"] <= t < w["endTime"]:
                return True
        return False

    def _batch_size():
        """Return the number of entities to spawn this arrival."""
        n = max(1, entities_per_arrival)
        if batch_dist == "poisson":
            return max(1, int(random.expovariate(1.0 / n) if n > 0 else 1))
        elif batch_dist == "uniform":
            return max(1, int(random.uniform(max(1, n - 1), n + 1)))
        else:
            return n  # deterministic

    def _exec_hook(snippet, entity_attrs):
        """Execute a user-supplied Python snippet in a sandboxed local scope."""
        if snippet:
            try:
                exec(snippet, {"env": env, "entity": entity_attrs, "random": random})
            except Exception as exc:
                pass  # hook errors must not abort simulation

    def _should_stop():
        """Check all termination conditions."""
        if env.now > DURATION:
            return True
        if duration_limit is not None and env.now >= duration_limit:
            return True
        return False

    def spawn_batch():
        """Spawn one batch of entities; returns number actually spawned."""
        nonlocal count

        # ── onBeforeArrival hook ───────────────────────────────────────────────
        _exec_hook(hook_before_arrival, {})

        batch_n = _batch_size()
        spawned = 0
        for _ in range(batch_n):
            if max_entities is not None and count >= max_entities:
                # onDiscard hook
                _exec_hook(hook_on_discard, {"reason": "max_entities"})
                break

            eid = next_entity_id()
            total_arrived[0] += 1

            # Build entity attributes dict
            sampled_class = _sample_entity_class()
            entity_attrs = {
                "id": eid,
                "priority": priority_num,
                "entityClass": sampled_class,
                "arrivalTime": env.now if time_measure_start else None,
            }
            # Bind custom labels (Attribute Binding)
            for lbl in entity_labels:
                entity_attrs[lbl["key"]] = lbl["value"]

            # ── onAtExit hook ──────────────────────────────────────────────────
            _exec_hook(hook_at_exit, entity_attrs)

            log_event(env.now, eid, node_id, label, "arrived")
            targets = get_next_targets(node_id, routing_mode)
            for target_id in targets:
                env.process(entity_process(env, eid, target_id, resources, entity_attrs))

            count += 1
            spawned += 1
        return spawned

    count = 0

    # ── Discard if source starts outside shift window ──────────────────────────
    # (wait until first shift window opens)
    if shift_windows:
        first_open = min(w["startTime"] for w in shift_windows)
        if env.now < first_open:
            yield env.timeout(first_open - env.now)

    if schedule:
        # ── Table-Driven (schedule-based) arrivals ─────────────────────────────
        last_period_offset = 0.0
        while True:
            for entry in sorted(schedule, key=lambda e: e["simTime"]):
                fire_at = last_period_offset + entry["simTime"]
                if fire_at > DURATION:
                    return
                if duration_limit is not None and fire_at >= duration_limit:
                    return
                delay = max(0.0, fire_at - env.now)
                yield env.timeout(delay)
                if _should_stop():
                    return
                if not _in_shift(env.now):
                    _exec_hook(hook_on_discard, {"reason": "shift_blocked"})
                    continue
                for _ in range(entry.get("count", 1)):
                    if max_entities is not None and count >= max_entities:
                        return
                    spawn_batch()
            if not schedule_recurring:
                break
            last_period_offset += max(e["simTime"] for e in schedule)

    elif distribution == "nhpp_thinning":
        # ── NHPP – Lewis-Shedler Thinning ─────────────────────────────────────
        if not nhpp_rates:
            return
        while not _should_stop():
            if max_entities is not None and count >= max_entities:
                break
            # Drive thinning process; it yields env.timeout internally
            yield from _nhpp_thinning(env, nhpp_rates, majorizing_rate)
            if _should_stop():
                break
            if _in_shift(env.now):
                spawn_batch()

    elif distribution == "nhpp_time_transform":
        # ── NHPP – Non-linear Time Transformation ──────────────────────────────
        if not nhpp_rates:
            return
        while not _should_stop():
            if max_entities is not None and count >= max_entities:
                break
            yield from _nhpp_time_transform(env, nhpp_rates, DURATION)
            if _should_stop():
                break
            if _in_shift(env.now):
                spawn_batch()

    else:
        # ── Stochastic rate-based (HPP: exponential / uniform / normal / …) ───
        while True:
            inter_arrival = sample(distribution, 1.0 / arrival_rate if arrival_rate > 0 else 1.0)
            yield env.timeout(inter_arrival)
            if _should_stop():
                break
            if max_entities is not None and count >= max_entities:
                break
            if not _in_shift(env.now):
                _exec_hook(hook_on_discard, {"reason": "shift_blocked"})
                continue
            spawn_batch()

def tick_emitter(env, resources, total_arrived):
    while True:
        yield env.timeout(TICK_INTERVAL)
        snap = snapshot_stats(env)
        recent = list(log_buffer)
        log_buffer.clear()
        
        tick = {
            "type": "tick",
            "data": {
                "simTime": env.now,
                "wallElapsed": 0,
                "totalArrived": total_arrived[0],
                "totalCompleted": stats_total_completed(snap),
                "nodeStats": snap,
                "recentLogs": recent,
            }
        }
        emit_sim_tick(json.dumps(tick))

def stats_total_completed(snap):
    for nid, s in snap.items():
        if NODE_CONFIG[nid]["nodeType"] == "sink":
            return s["entitiesOut"]
    return 0

def breakdown_process(env, node_id, resources):
    cfg = NODE_CONFIG[node_id]
    params = cfg["params"]
    label = cfg["label"]
    s = stats[node_id]
    
    mtbf = params.get("meanTimeBetweenFailures")
    if not mtbf:
        return
        
    repair_mean = params.get("repairTimeMean", 1)
    repair_dist = params.get("repairDistribution", "exponential")
    repairman_id = params.get("repairmanNodeId")
    repair_pri = params.get("repairPriority", 1)
    
    res = resources[node_id]
    
    while True:
        time_to_fail = sample("exponential", mtbf)
        yield env.timeout(time_to_fail)
        
        # Breakdown occurred
        log_event(env.now, 0, node_id, label, "breakdown")
        s["breakdownCount"] = s.get("breakdownCount", 0) + 1
        start_downtime = env.now
        
        # Seize all slots with extremely high priority (-999) to simulate breakdown
        reqs = [res.request(priority=-999) for _ in range(res.capacity)]
        yield env.all_of(reqs)
        
        # Do repair
        if repairman_id and repairman_id in resources:
            rep_res = resources[repairman_id]
            with rep_res.request(priority=repair_pri) as rep_req:
                yield rep_req
                repair_time = sample(repair_dist, repair_mean)
                yield env.timeout(repair_time)
        else:
            repair_time = sample(repair_dist, repair_mean)
            yield env.timeout(repair_time)
            
        # Repaired
        for req in reqs:
            res.release(req)
            
        downtime = env.now - start_downtime
        s["totalDowntime"] = s.get("totalDowntime", 0.0) + downtime
        log_event(env.now, 0, node_id, label, "repaired")

def run_simulation():
    env = simpy.Environment()
    resources = {}
    total_arrived = [0]

    init_stats()

    for nid, cfg in NODE_CONFIG.items():
        n_type = cfg["nodeType"]
        if n_type in ("resource", "priority_resource"):
            cap = cfg["params"].get("capacity", 1)
            is_pre = cfg["params"].get("isPreemptive", False)
            if is_pre:
                resources[nid] = simpy.PreemptiveResource(env, capacity=max(1, cap))
            else:
                resources[nid] = simpy.PriorityResource(env, capacity=max(1, cap))
        elif n_type == "store":
            cap = cfg["params"].get("capacity", -1)
            c = max(1, cap) if cap > 0 else float('inf')
            if cfg["params"].get("isPriority", False):
                resources[nid] = simpy.PriorityStore(env, capacity=c)
            elif cfg["params"].get("filterEnabled", False):
                resources[nid] = simpy.FilterStore(env, capacity=c)
            else:
                resources[nid] = simpy.Store(env, capacity=c)
        elif n_type in ("event_trigger", "any_of", "all_of"):
            global_events[nid] = env.event()

    for nid, cfg in NODE_CONFIG.items():
        if cfg["nodeType"] == "source":
            env.process(source_process(env, nid, resources, total_arrived))
        elif cfg["nodeType"] in ("resource", "priority_resource"):
            if cfg["params"].get("meanTimeBetweenFailures"):
                env.process(breakdown_process(env, nid, resources))

    env.process(tick_emitter(env, resources, total_arrived))

    env.run(until=DURATION)

    snap = snapshot_stats(env)
    remaining_logs = list(log_buffer)

    bottleneck_id = ""
    bottleneck_label = ""
    max_wait = -1
    for nid, s in snap.items():
        if NODE_CONFIG[nid]["nodeType"] in ("resource", "queue"):
            if s["avgWaitTime"] > max_wait:
                max_wait = s["avgWaitTime"]
                bottleneck_id = nid
                bottleneck_label = NODE_CONFIG[nid]["label"]

    result = {
        "type": "complete",
        "data": {
            "simType": "human_queue", # Extracted correctly ideally, but fine for Bank Tellers
            "totalSimTime": env.now,
            "totalArrived": total_arrived[0],
            "totalCompleted": stats_total_completed(snap),
            "bottleneckNodeId": bottleneck_id,
            "bottleneckLabel": bottleneck_label,
            "nodeStats": snap,
            "timeline": [],
            "logs": remaining_logs,
        }
    }
    
    emit_sim_result(json.dumps(result))

run_simulation()
`;
